#!/bin/bash

#Comprueba si existe el punto de montaje de veleta /media

	ls /media | grep -i "veleta" > /dev/null
	if [ $? -ne 0 ];then
		mkdir /media/veleta
	fi

#Comprueba si existe la linea de montaje de veleta en /etc/fstab

	cat /etc/fstab | grep -i "veleta.grx" > /dev/null
	if [ $? -ne 0 ];then
		echo "//veleta.grx/usuarios /media/veleta  cifs  noauto,soft,sec=krb5,iocharset=utf8,user  0 0" >> /etc/fstab
	fi
#Creamos el archivo de logs
	
	if [ ! -d "/var/log/grx" ];then
		mkdir /var/log/grx
	fi
	if [ ! -f "/var/log/grx/grx-veleta.log" ];then
		touch /var/log/grx/grx-veleta.log
		chmod 555 /var/log/grx/grx-veleta.log
	fi

	cat /etc/skel/.profile | grep -i "init_veleta.sh" > /dev/null
	if [ $? -ne 0 ];then
		#Insertamos la ejecución del script de inicio de veleta init_veleta.sh en /etc/skel/.profile
		echo '# ejecuta el script de inicio del sistema de copias de seguridad' >> /etc/skel/.profile
		echo '$HOME/.grx/init_veleta.sh >> /var/log/grx/grx-veleta.log' >> /etc/skel/.profile
	fi



exit 0
